### ISSUE TITLE
Images not pull

### ISSUE THREAD

**Issue by Damasker** [etiennetremel/kubernetes-nginx-multisite-example#1]
pod/proxy-5k4h9                          0/1     ImagePullBackOff   0          21s
pod/proxy-wwvm4                          0/1     ImagePullBackOff   0          21s
pod/site-one-l8fhl                       0/1     ImagePullBackOff   0          20s
pod/site-one-xw4jj                       0/1     ImagePullBackOff   0          20s
pod/site-two-99mvk                       0/1     ImagePullBackOff   0          19s
pod/site-two-kwmq5                       0/1     ImagePullBackOff   0          19s

**Comment by etiennetremel** [comment]
HI @Damasker, this repository is super old, I would advise checking the [nginx-ingress controller](https://github.com/kubernetes/ingress-nginx) instead.
